# Generated by Django 4.2.4 on 2023-08-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_institution_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='url',
            field=models.URLField(blank=True, max_length=9999, null=True),
        ),
    ]
