# Generated by Django 4.2.4 on 2023-08-16 14:35

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_document_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='url',
            field=models.TextField(blank=True, help_text='Enter either a valid URL, or "n.a." if not available.', null=True, validators=[core.models.validate_url]),
        ),
    ]
