# Generated by Django 4.2.4 on 2023-08-18 16:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_document_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authenticated_content', ckeditor.fields.RichTextField(help_text='Home page content that will appear to logged-in users.')),
                ('unauthenticated_content', ckeditor.fields.RichTextField(help_text='Home page content that will appear to new users above the register/login links.')),
            ],
            options={
                'verbose_name_plural': 'home page settings',
            },
        ),
    ]
