name: CI

on:
  pull_request:
    paths-ignore:
      - "**/README.md"
      - "**/dependabot.yml"
    branches:
      - main

concurrency: CI

jobs:
  build-ci:
    name: "Build and CI Test"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt

      - name: Build and test
        run: |
          cp .env-example .env
          python3 manage.py check
          python3 manage.py test

  automerge:
    needs: build-ci
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3.9
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}